// This file is generated by backend/scripts/generate_api_contract.py.
// Do not edit it by hand. Regenerate it after changing FastAPI wire schemas.

export type AnswerReviewCase = {
  "question_index": number
  "question": string
  "correct_answer": string
  "accepted_answers"?: string[]
  "answer_groups"?: string[][]
  "required_group_count": number
  "student_answer": string
  "explanation"?: string
}

export type AnswerReviewDecision = {
  "question_index": number
  "verdict": "correct" | "incorrect" | "uncertain"
  "confidence": number
  "reason": string
}

export type AnswerReviewRequest = {
  "cases": AnswerReviewCase[]
}

export type AnswerReviewResponse = {
  "decisions": AnswerReviewDecision[]
}

export type Quiz = {
  "title": string
  "questions": QuizQuestion[]
}

export type QuizQuestion = {
  "question_type": "multiple_choice" | "true_false" | "short_answer"
  "question": string
  "choices": string[]
  "correct_index": number
  "correct_answer": string
  "accepted_answers": string[]
  "grading": ShortAnswerGradingSpec
  "explanation": string
  "source_pages": number[]
}

export type ShortAnswerGradingSpec = {
  "grading_version": 2
  "grading_mode": "none" | "concepts" | "exact" | "numeric"
  "answer_groups": string[][]
  "required_group_count": number
  "numeric_value": number
  "numeric_tolerance": number
  "numeric_unit": string
}

export type SourcePageResponse = {
  "pdf_sha256": string
  "page_number": number
  "text": string
}

export type UploadPageSummary = {
  "page_number": number
  "character_count": number
  "preview": string
}

export type UploadResponse = {
  "filename": string | null
  "pdf_sha256": string
  "page_count": number
  "character_count": number
  "extractable_page_count": number
  "scanned_likely": boolean
  "warning": string | null
  "pages": UploadPageSummary[]
}

export const API_ROUTES = [
  "GET /",
  "GET /api/admin/metrics",
  "GET /api/documents/{document_sha256}/pages/{page_number}",
  "GET /api/health",
  "POST /api/answers/review",
  "POST /api/documents/upload",
  "POST /api/quizzes/generate",
] as const

export type ApiRoute = (typeof API_ROUTES)[number]
