// This file is generated by backend/scripts/generate_api_contract.py.
// Do not edit it by hand. Regenerate it after changing FastAPI wire schemas.

export type AnswerReviewCase = {
  "question_index": number
  "question": string
  "correct_answer": string
  "accepted_answers"?: string[]
  "answer_groups"?: string[][]
  "required_group_count": number
  "student_answer": string
  "explanation"?: string
}

export type AnswerReviewDecision = {
  "question_index": number
  "verdict": "correct" | "incorrect" | "uncertain"
  "confidence": number
  "reason": string
}

export type AnswerReviewRequest = {
  "cases": AnswerReviewCase[]
}

export type AnswerReviewResponse = {
  "decisions": AnswerReviewDecision[]
}

export type HistoryCreate = {
  "quiz_title": string
  "source_filename": string
  "document_sha256"?: string | null
  "difficulty": "easy" | "medium" | "hard"
  "question_type": "multiple_choice" | "true_false" | "short_answer" | "mixed"
  "question_count": number
  "score": number
  "percentage": number
  "quiz_data": {
  [key: string]: unknown
}
  "selected_answers": {
  [key: string]: number | string
}
}

export type HistoryRow = {
  "id": string
  "user_id": string
  "quiz_title": string
  "source_filename": string
  "document_sha256"?: string | null
  "difficulty": string
  "question_type": string
  "question_count": number
  "score": number
  "percentage": number
  "quiz_data": unknown
  "selected_answers": {
  [key: string]: number | string
}
  "created_at": string
}

export type HistoryCursor = {
  "createdAt": string
  "id": string
}

export type HistoryPage = {
  "items": HistoryRow[]
  "totalCount": number | null
  "hasMore": boolean
  "nextCursor": HistoryCursor | null
}

export type CardCreate = {
  "question_type": "multiple_choice" | "true_false" | "short_answer"
  "question": string
  "answer": {
  [key: string]: unknown
}
  "choices"?: string[] | null
  "explanation"?: string | null
  "source_filename"?: string | null
  "document_sha256"?: string | null
  "source_pages"?: number[]
}

export type CardRow = {
  "question_type": "multiple_choice" | "true_false" | "short_answer"
  "question": string
  "answer": {
  [key: string]: unknown
}
  "choices"?: string[] | null
  "explanation"?: string | null
  "source_filename"?: string | null
  "document_sha256"?: string | null
  "source_pages"?: number[]
  "id": string
  "deck_id": string
  "created_at": string
  "updated_at": string
}

export type DeckCreate = {
  "name": string
  "description"?: string | null
  "cards"?: CardCreate[]
}

export type DeckUpdate = {
  "name"?: string | null
  "description"?: string | null
}

export type CardBatchCreate = {
  "cards": CardCreate[]
}

export type DeckSummary = {
  "id": string
  "name": string
  "description": string | null
  "card_count": number
  "created_at": string
  "updated_at": string
}

export type DeckDetail = {
  "id": string
  "name": string
  "description": string | null
  "card_count": number
  "created_at": string
  "updated_at": string
  "cards": CardRow[]
}

export type PdfJobResponse = {
  "job_id": string
  "filename": string
  "status": "queued" | "processing" | "succeeded" | "failed" | "cancelled"
  "completed_pages": number
  "total_pages": number | null
  "expires_at": string
  "error": string | null
  "result"?: UploadResponse | null
  "selected_pages"?: number[]
  "source_sha256"?: string | null
  "reused_pages"?: number
}

export type PdfJobList = {
  "jobs": PdfJobResponse[]
  "supports_page_selection"?: boolean
  "supports_page_reuse"?: boolean
  "supports_cached_selection"?: boolean
}

export type CachedSelectionRequest = {
  "source_sha256": string
  "page_selection"?: string
}

export type Quiz = {
  "title": string
  "questions": QuizQuestion[]
}

export type QuizQuestion = {
  "question_type": "multiple_choice" | "true_false" | "short_answer"
  "question": string
  "choices": string[]
  "correct_index": number
  "correct_answer": string
  "accepted_answers": string[]
  "grading": ShortAnswerGradingSpec
  "explanation": string
  "source_pages": number[]
}

export type ShortAnswerGradingSpec = {
  "grading_version": 2
  "grading_mode": "none" | "concepts" | "exact" | "numeric"
  "answer_groups": string[][]
  "required_group_count": number
  "numeric_value": number
  "numeric_tolerance": number
  "numeric_unit": string
}

export type SourcePageResponse = {
  "pdf_sha256": string
  "page_number": number
  "text": string
}

export type UploadPageSummary = {
  "page_number": number
  "character_count": number
  "preview": string
}

export type UploadResponse = {
  "filename": string | null
  "pdf_sha256": string
  "page_count": number
  "character_count": number
  "extractable_page_count": number
  "scanned_likely": boolean
  "warning": string | null
  "pages": UploadPageSummary[]
}

export const API_ROUTES = [
  "DELETE /api/decks/{deck_id}",
  "DELETE /api/documents/jobs/{job_id}",
  "DELETE /api/quiz-history/{entry_id}",
  "GET /",
  "GET /api/admin/metrics",
  "GET /api/decks",
  "GET /api/decks/{deck_id}",
  "GET /api/documents/jobs",
  "GET /api/documents/jobs/{job_id}",
  "GET /api/documents/{document_sha256}/pages/{page_number}",
  "GET /api/health",
  "GET /api/quiz-history",
  "GET /api/quiz-history/document",
  "PATCH /api/decks/{deck_id}",
  "POST /api/answers/review",
  "POST /api/decks",
  "POST /api/decks/{deck_id}/cards",
  "POST /api/documents/jobs/reuse",
  "POST /api/documents/upload",
  "POST /api/quiz-history",
  "POST /api/quizzes/generate",
] as const

export type ApiRoute = (typeof API_ROUTES)[number]
